repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
        exclude: ^layouts/_default/rss\.xml$
      - id: check-yaml
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: no-commit-to-branch
